### ISSUE TITLE
Doesn't work with v0.5

### ISSUE THREAD

**Issue by musm** [carnaval/IACA.jl#2]
Not exactly sure what else is a problem, but for sure this line
https://github.com/carnaval/IACA.jl/blob/master/src/IACA.jl#L24
is causing problems.

**Comment by vchuravy** [comment]
I was looking into updating this for v0.6, but I am running into a seqfault at https://github.com/carnaval/IACA.jl/blob/4a03df14de8564a8b87c85957081db916d7ac2e8/src/IACA.jl#L62
@carnaval do you have time to update IACA or should I spend some time on figuring out what is going wrong?
